# Generated by Django 4.2.5 on 2023-09-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('capellido', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Local',
        ),
    ]
