# Generated by Django 4.2.5 on 2023-09-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_estudiantes_rename_curso_local'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Local',
            new_name='Curso',
        ),
    ]
