# Generated by Django 4.2.5 on 2023-09-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_entregable_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
