# Generated by Django 4.2.5 on 2023-09-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_entregable_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='email',
            field=models.EmailField(default=[], max_length=100),
        ),
    ]
